apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: mysql-db
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
  name: mysql-db
  namespace: yc-blog-namespace
spec:
  clusterIP: 10.96.128.11
  selector:
    app: mysql-blog
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql-blog
  replicas: 1
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql-blog
    spec:
      containers:
        - name: mysql
          image: andrey1pf/panda-coder-sql:dev
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pi31415926
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
